[package]
name = "utils"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
migration = { path = "../migration" }

axum = { workspace = true }
tower = { workspace = true, features = ["util"] }
sea-orm = { workspace = true, features = ["sqlx-sqlite"] }
