[package]
name = "api"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
axum = "0.7.1"
tower = "0.4.13"
tower-http = { version = "0.5.0", features = ["fs"] }
tower-cookies = "0.10.0"
anyhow = "1.0.75"
dotenvy = "0.15.7"
tera = "1.19.1"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# local dependencies
app = { path = "../app" }
models = { path = "../models" }
