name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable, beta]
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy, llvm-tools-preview

      - uses: Swatinem/rust-cache@v2

      - name: Check and run lint
        run: cargo check && cargo fmt && cargo clippy

      - run: cargo build

