[package]
name = "models"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
serde = { workspace = true }
serde_json = "1"
sea-orm = { workspace = true, features = [
  "sqlx-postgres",
  "sqlx-sqlite",
  "runtime-tokio-rustls",
  "macros",
] }
utoipa = { workspace = true }
